#pragma once
void HandleRegisterFlight();
void HandleAuthorization();
void HandleRegistration();
void HandleRegistrationMember();
void HandleRegistrationHelicopter();
void HandleRegistrationCommando();
void HandleRegistrationAdmin();
void HandleMainMenu();
void HandleRegistrationNewUser();
void HandleStartWindow();
void UiControllerInit();
void HandleCrewMemberInfo();
void HandleFlightsInfo();
void HandleHelicopterInfo();
void HandleFlightsInfoByDate();
void HandleDeleteFlight();
int GetYesNo();
int GetInteger();
char* GetData();
int IsValidNumber(char* string);
void PrintMatrix(char*** matrix, char** columnsNames, int rawsCount, int columnsCount);
int TryLogin(char* login, char* password);